repoURL: https://charts.bitnami.com/bitnami
chart: postgresql
targetRevision: 18.6.6
values: |
  auth:
    database: backstage
    username: backstage
    password: backstage
  primary:
    persistence:
      enabled: false
